# Generated by Django 3.2.20 on 2024-03-18 00:31

import clothes.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_model', models.CharField(max_length=120)),
                ('file_extension', models.CharField(blank=True, max_length=120, null=True)),
                ('width', models.BigIntegerField()),
                ('heigth', models.BigIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=clothes.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=120)),
                ('size', models.BigIntegerField()),
                ('segmantation_colour', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
            ],
        ),
    ]
