# Generated by Django 3.2.20 on 2024-03-18 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_rename_heigth_clothes_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentation',
            name='clothes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes'),
        ),
    ]
